language: cpp
os:
    - linux
compiler:
    - clang
env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
install:
    - wget --quiet -O - https://raw.githubusercontent.com/r-lyeh/depot/master/travis.pre.sh   | bash -x
before_script:
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
      - cmake --build .
script:
      - pwd
      - make
