language: cpp
os:
    - linux
compiler:
    - gcc
    - clang
env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
install:
    - wget --quiet -O - https://raw.githubusercontent.com/r-lyeh/depot/master/travis.pre.sh   | bash -x
before_script:
      - mkdir build
      - cd build
      - cmake ..
script:
      - pwd
      - make
