version: 1.0.{build}
image:
- Visual Studio 2017
- Visual Studio 2015
configuration: Release
platform:
- x86
- x64
before_build:
  - echo Running cmake...
  - cd c:\projects\radix
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -G "Visual Studio 15 2017 Win64"
build:
  project: c:\projects\radix\Radix.sln
  parallel: true
  verbosity: minimal
only_commits:
  message: /build/