version: 1.0.{build}
image:
- Visual Studio 2017
configuration: RELEASE
platform:
- x64
before_build:
  - echo Running cmake...
  - cd c:\projects\radix
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -G "Visual Studio 15 2017 Win64"
build:
  project: c:\projects\radix\Radix.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: \*
    name: Radix_x64
    type: zip
  - path: assets
    name: assets
    type: zip
  - path: documentation\html\*
    name: Documentation_html
    type: zip
  - path: documentation\*
    name: Documentation_all
    type: zip
deploy:
  provider: GitHub
  release: v$(appveyor_build_version)
  description: 'Radix'
  auth_token:
    secure: Jj2VTZV7xlAPGxeAUS5HMDRFzgwdkCSMJxUAl7icI7TeBXTR/mH7fIG9+tPt/oRG
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true